export const ADD_POST = 'ADD_POST';
export const ADD_POST_REQUEST = 'ADD_POST_REQUEST';
export const FETCH_POST_REQUEST = 'FETCH_POST_REQUEST';
export const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST';
export const ADD_POSTS = 'ADD_POSTS';
export const DELETE_POST = 'DELETE_POST';
export const DELETE_POST_REQUEST = 'DELETE_POST_REQUEST';
